-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 12:19:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vlute_course_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vlute_course_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vlute_course_manager` ;
USE `vlute_course_manager` ;

-- -----------------------------------------------------
-- Table `vlute_course_manager`.`authenticate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`authenticate` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`user` (
  `user_id` INT UNSIGNED NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `account_type` VARCHAR(10) NOT NULL DEFAULT 'student',
  UNIQUE INDEX `userId_UNIQUE` (`user_id` ASC),
  CONSTRAINT `fk_user_userId`
    FOREIGN KEY (`user_id`)
    REFERENCES `vlute_course_manager`.`authenticate` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`major` (
  `major_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `major_title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`major_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`student` (
  `user_id` INT UNSIGNED NOT NULL,
  `student_id` VARCHAR(8) NOT NULL COMMENT 'Mã số sinh viên.',
  `major_id` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `student_id_UNIQUE` (`student_id` ASC),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_student_userId`
    FOREIGN KEY (`user_id`)
    REFERENCES `vlute_course_manager`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_majorId`
    FOREIGN KEY (`major_id`)
    REFERENCES `vlute_course_manager`.`major` (`major_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`teacher` (
  `user_id` INT UNSIGNED NOT NULL,
  `major_id` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `fk_teacher_userId`
    FOREIGN KEY (`user_id`)
    REFERENCES `vlute_course_manager`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacher_majorId`
    FOREIGN KEY (`major_id`)
    REFERENCES `vlute_course_manager`.`major` (`major_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(45) NOT NULL,
  `course_code` VARCHAR(6) NOT NULL,
  `credit_count` TINYINT NOT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `className_UNIQUE` (`course_name` ASC),
  UNIQUE INDEX `course_code_UNIQUE` (`course_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`enroll_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`enroll_session` (
  `enroll_session_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `start_at` DATE NOT NULL,
  `end_at` DATE NOT NULL,
  PRIMARY KEY (`enroll_session_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`course_enroll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`course_enroll` (
  `course_id` INT NOT NULL,
  `student_id` VARCHAR(8) NOT NULL,
  `enroll_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `enroll_session_id` INT NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_courseEnroll_studentId_idx` (`student_id` ASC),
  INDEX `fk_courseEnroll_enrollSessionId_idx` (`enroll_session_id` ASC),
  CONSTRAINT `fk_courseRnroll_courseId`
    FOREIGN KEY (`course_id`)
    REFERENCES `vlute_course_manager`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_courseEnroll_studentId`
    FOREIGN KEY (`student_id`)
    REFERENCES `vlute_course_manager`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courseEnroll_enrollSessionId`
    FOREIGN KEY (`enroll_session_id`)
    REFERENCES `vlute_course_manager`.`enroll_session` (`enroll_session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`manager` (
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_manager_userId`
    FOREIGN KEY (`user_id`)
    REFERENCES `vlute_course_manager`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `vlute_course_manager`.`authenticate`(username, password) VALUES ("conkgytt", "$2a$11$PtC5OUnz9XegCzRmi7toWee5GJNTNf4srQyvXeMgWdFXRec1azMNW");

SELECT * FROM `vlute_course_manager`.`authenticate`;
