-- MySQL Script generated by MySQL Workbench
-- Tue Nov 14 23:59:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vlute_course_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vlute_course_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vlute_course_manager` ;
USE `vlute_course_manager` ;

-- -----------------------------------------------------
-- Table `vlute_course_manager`.`authenticate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vlute_course_manager`.`authenticate` ;

CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`authenticate` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vlute_course_manager`.`major` ;

CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`major` (
  `major_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `major_title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`major_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vlute_course_manager`.`user` ;

CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`user` (
  `user_id` INT UNSIGNED NOT NULL,
  `major_id` INT UNSIGNED NULL,
  `student_id` VARCHAR(8) NULL,
  `fullname` VARCHAR(45) NULL,
  `avatar` VARCHAR(100) NULL DEFAULT 'D:\\Workspace\\.NET\\vlute-course-manager\\assets\\images\\formHome\\user.png',
  `role` VARCHAR(10) NOT NULL DEFAULT 'student',
  UNIQUE INDEX `userId_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_majorId_idx` (`major_id` ASC) VISIBLE,
  UNIQUE INDEX `student_id_UNIQUE` (`student_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_userId`
    FOREIGN KEY (`user_id`)
    REFERENCES `vlute_course_manager`.`authenticate` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_majorId`
    FOREIGN KEY (`major_id`)
    REFERENCES `vlute_course_manager`.`major` (`major_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vlute_course_manager`.`subject` ;

CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`subject` (
  `subject_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `major_id` INT UNSIGNED NOT NULL,
  `subject_name` VARCHAR(60) NOT NULL,
  `theory_credit_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `practice_credit_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`subject_id`),
  INDEX `fk_subject_majorId_idx` (`major_id` ASC) VISIBLE,
  CONSTRAINT `fk_subject_majorId`
    FOREIGN KEY (`major_id`)
    REFERENCES `vlute_course_manager`.`major` (`major_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vlute_course_manager`.`course` ;

CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `subject_id` INT UNSIGNED NOT NULL,
  `teacher_id` INT UNSIGNED NOT NULL,
  `course_name` VARCHAR(45) NOT NULL,
  `course_number` INT NOT NULL DEFAULT 0,
  `course_code` VARCHAR(6) NOT NULL,
  `practice` TINYINT NOT NULL DEFAULT 0,
  `max_member_count` INT NOT NULL DEFAULT 30,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `className_UNIQUE` (`course_name` ASC) VISIBLE,
  UNIQUE INDEX `course_code_UNIQUE` (`course_code` ASC) VISIBLE,
  INDEX `fk_coursel_teacherId_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `fk_course_subjectId_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_teacherId`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `vlute_course_manager`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_course_subjectId`
    FOREIGN KEY (`subject_id`)
    REFERENCES `vlute_course_manager`.`subject` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`enroll_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vlute_course_manager`.`enroll_session` ;

CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`enroll_session` (
  `enroll_session_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL,
  `start_at` DATE NOT NULL,
  `end_at` DATE NOT NULL,
  PRIMARY KEY (`enroll_session_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`course_enroll`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vlute_course_manager`.`course_enroll` ;

CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`course_enroll` (
  `course_id` INT NOT NULL,
  `student_id` VARCHAR(8) NOT NULL,
  `enroll_session_id` INT NOT NULL,
  `enroll_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_courseEnroll_enrollSessionId_idx` (`enroll_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_courseEnroll_courseId`
    FOREIGN KEY (`course_id`)
    REFERENCES `vlute_course_manager`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_courseEnroll_enrollSessionId`
    FOREIGN KEY (`enroll_session_id`)
    REFERENCES `vlute_course_manager`.`enroll_session` (`enroll_session_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vlute_course_manager`.`course_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vlute_course_manager`.`course_session` ;

CREATE TABLE IF NOT EXISTS `vlute_course_manager`.`course_session` (
  `course_id` INT NOT NULL,
  `enroll_session_id` INT NOT NULL,
  INDEX `fk_courseSession_courseId_idx` (`course_id` ASC) VISIBLE,
  INDEX `fk_courseSession_enrollSessionId_idx` (`enroll_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_courseSession_courseId`
    FOREIGN KEY (`course_id`)
    REFERENCES `vlute_course_manager`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_courseSession_enrollSessionId`
    FOREIGN KEY (`enroll_session_id`)
    REFERENCES `vlute_course_manager`.`enroll_session` (`enroll_session_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
